Repository fasten-project/fasten-web, pull requests merged in 2021-02, with the labels that each got.

#49 Removed # from base url
  src/index.tsx
  src/routes/Home/Home.tsx
Labels: Priority: Low, bug, enhancement

#50 Revert "Removed # from base url"
  src/index.tsx
  src/routes/Home/Home.tsx
Labels: Priority: Critical, bug

#53 Version Picker Tab
  src/components/Package/Package.tsx
  src/components/PackageTable/PackageTable.tsx
  src/requests/payloads/package-versions-payload.ts
  src/requests/services/package.ts
Labels: Priority: High, enhancement, good first issue

#54 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: Priority: Low, enhancement

#56 Readable callables
  src/components/Package/Package.tsx
  src/components/PackageTable/PackageTable.tsx
  src/requests/payloads/package-callable-payload.ts
Labels: Priority: Medium, enhancement

#57 Quickfix: Make line start and end in callable schema nullable
  src/requests/payloads/package-callable-payload.ts
Labels: Priority: High, bug

#58 Add loading spinner to Package page (#52)
  package.json
  src/routes/Package/Package.styled.tsx
  src/routes/Package/Package.tsx
  yarn.lock
Labels: Priority: Low, enhancement
